name: build and test feature branch
on:
  pull_request:
    branches: [ develop ]
    types: [ opened, reopened ]
jobs: 
  build-feature:
    runs-on: ubuntu-latest
    steps:
      #############################################################
      # 2- dowload code from feature branch , setup java 8 and check that source code is buildable
      ########################################################
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          
      - name: pull and checkout from git repository
        run: |
           echo "pulling and checking out from git repository"

      - name: setup java 21 
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
      - name: Set Environment Variables
        run: |
          echo "DB_URL=${{ secrets.DB_URL_DEVELOP }}" >> $GITHUB_ENV
          echo "DB_USER=${{ secrets.DB_USER_DEVELOP }}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD_DEVELOP }}" >> $GITHUB_ENV

      - name: Cache Maven dependencies
        uses: actions/cache@v4.2.3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: build with maven
        run: |
          mvn clean test package
          echo "build with maven"



    
      