name: Deploy a EC2 con Docker Compose

on:
  repository_dispatch:
    types: [deploy-app-event]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Get SHA from repository-dispatch payload
        id: get_sha
        run: echo "SHA=${{ github.event.client_payload.sha }}" >> $GITHUB_ENV  # Extraemos el SHA del payload

      - name: SSH to EC2 and update container
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST_DEV }}
          username: ${{ secrets.EC2_USER_DEV }}
          key: ${{ secrets.EC2_SSH_KEY_DEV }}
          script: |
            cd /home/ec2-user/claimhere
            docker pull ghcr.io/jhoel2002/cutomer-back:${{ env.SHA }} # Descarga la última imagen
            docker images
            export TAG=${{ env.SHA }} 
            docker-compose down -v
            docker-compose up --detach
            docker system prune -a -f