name: Control de RDS (On/Off)

on:
  workflow_dispatch:
    inputs:
      estado:
        description: '1 para encender, 0 para apagar'
        required: true
        default: '1'
##prueba de cambio

jobs:
  controlar-rds:
    runs-on: ubuntu-latest
    steps:
      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Cambiar estado de la instancia RDS
        env:
          RDS_INSTANCE_ID: ${{ secrets.RDS_INSTANCE_ID }}
        run: |
          if [ "${{ github.event.inputs.estado }}" = "1" ]; then
            echo "Encendiendo la instancia RDS..."
            aws rds start-db-instance --db-instance-identifier "$RDS_INSTANCE_ID"
          elif [ "${{ github.event.inputs.estado }}" = "0" ]; then
            echo "Apagando la instancia RDS..."
            aws rds stop-db-instance --db-instance-identifier "$RDS_INSTANCE_ID"
          else
            echo "Valor de estado no válido: ${{ github.event.inputs.estado }}"
            exit 1
          fi
